"use client";
import {useState} from "react";
const categories=[["Healthcare","Doctors, clinics & diagnostics","🩺"],["Salon & Beauty","Salons, spas & wellness","✂️"],["Restaurants","Tables, dining & waitlists","🍽️"],["Services","Tutors, consultants & more","⚡"]];
const businesses=[["Dr. Mehta Clinic","General physician","4.9","₹500","12 min"],["Glow Studio","Hair & beauty","4.8","₹700","8 min"],["The Table House","Restaurant","4.7","₹1,200","15 min"],["FitCore Wellness","Fitness & wellness","4.9","₹900","10 min"]];
export default function Home(){const [mode,setMode]=useState<"customer"|"business">("customer");const [category,setCategory]=useState("All");return <main>
<header><div className="brand"><span className="mark">B</span><span>BookFlow</span></div><nav><a>Discover</a><a>Bookings</a><a>For Business</a><button className="ghost">Sign in</button><button className="primary" onClick={()=>setMode(mode==="customer"?"business":"customer")}>{mode==="customer"?"Business login":"Customer view"}</button></nav></header>
<section className="hero"><div className="hero-copy"><div className="eyebrow">ONE PLATFORM · EVERY APPOINTMENT</div><h1>Book your time.<br/><em>Not your queue.</em></h1><p>Find doctors, salons, restaurants and everyday services, see real availability and book in seconds.</p><div className="search"><span>⌕</span><input placeholder="Search a service, business or area"/><button className="primary">Search</button></div><div className="quick"><span>Popular:</span><button onClick={()=>setCategory("Healthcare")}>Doctors</button><button onClick={()=>setCategory("Salon & Beauty")}>Salon</button><button onClick={()=>setCategory("Restaurants")}>Restaurants</button></div></div><div className="hero-card"><div className="card-top"><span>Today · Delhi</span><span className="live">● Live availability</span></div><div className="mini"><div className="avatar">DM</div><div><b>Dr. Mehta Clinic</b><small>General physician · 4.9 ★</small></div><span>›</span></div><div className="slots"><span>10:30</span><span className="active">11:00</span><span>11:30</span><span>12:00</span></div><div className="confirmed">✓ 11:00 AM available — instant booking</div></div></section>
<section className="section"><div className="section-head"><div><div className="eyebrow">EXPLORE</div><h2>What are you booking today?</h2></div><a>View all →</a></div><div className="categories">{categories.map(([t,s,i])=><button key={t} className={"category "+(category===t?"selected":"")} onClick={()=>setCategory(t)}><span className="cat-icon">{i}</span><b>{t}</b><small>{s}</small></button>)}</div></section>
<section className="section discover"><div className="section-head"><div><div className="eyebrow">NEAR YOU</div><h2>Available right now</h2></div><div className="filters"><button className="filter">⌖ Delhi</button><button className="filter">Any time⌄</button></div></div><div className="business-grid">{businesses.map(([n,t,r,p,d])=><article className="business" key={n}><div className="business-image">{n.slice(0,1)}</div><div className="business-body"><div className="line"><b>{n}</b><span>★ {r}</span></div><small>{t}</small><div className="meta"><span>{p} onwards</span><span>• {d} away</span></div><button className="book" onClick={()=>alert("Booking flow ready for "+n)}>View slots →</button></div></article>)}</div></section>
<section className="business-cta"><div><div className="eyebrow">FOR BUSINESS OWNERS</div><h2>Turn empty slots into booked hours.</h2><p>Manage appointments, staff, services, customers, reminders and payments from one place.</p></div><button className="primary">List your business →</button></section>
<footer><div className="brand"><span className="mark">B</span><span>BookFlow</span></div><span>Booking platform · MVP foundation</span><span>© 2026</span></footer>
</main>}
